/**
 * This is the main Web application configuration. Any writable
 * CWebApplication properties can be configured here.
 * Generated by AppManager
 *
 * @version <?php echo date('Y-m-d H:i:s') . "\n"; ?>
 */
 <?php echo "\n"; ?>