<?php
/**
 * This is the main Web application configuration. Any writable
 * CWebApplication properties can be configured here.
 * Generated by AppManager
 *
 * @version 2013-01-26 13:27:55
 */
 
return array(
    'basePath' => dirname(__FILE__).'/../../../..',
    'name' => 'Test App Manager',
    'modules' => array(
        'appManager' => array(
            'class' => 'application.modules.appManager.AppManagerModule',
        ),
    ),
);
